version: '3.10'

services:
  user-service:
    restart: always
    build: ./user_microservice/app/app
    volumes:
      - ./user_microservice/app/app:/app
    ports:
      - "5000:5000"
    networks:
      - app-tier
    depends_on:
      - db
    image: ms:v1.0.0
    container_name: user-service
  

networks:
  app-tier:
    driver: bridge
volumes:
  db-data:
    driver: local

  db:
    image: postgres:13
  volumes:
    - db-data:/var/lib/postgresql/data
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_DB: user_db
  ports:
    - "5432:5432"
  networks:
    - app-tier
  container_name: db
 
 
    Enter fullscreen mode