from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '45128c2b29a3'
down_revision = 'd40d151d8f8f'
branch_labels = None
depends_on = None

def upgrade():
    # commands auto generated by Alembic to upgrade your database go here.
    pass

def downgrade():
    # commands auto generated by Alembic to downgrade your database go here.
    pass

