services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80 
      - 8080:8080 # Puerto del panel de Traefik
      - 5432:5432  # Exponer el puerto 5432
      - 6379:6379  # Exponer el puerto 6379
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./_config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./_config/config.yml:/etc/traefik/config.yml:ro
      - ./_certs:/etc/certs:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik=true
    networks:
      - mired2

  ms1:
    image: ms1:1.0.1
    build: 
      context: /home/fede-caballero/UM/ingenieria/cuartoAnio/ingSoftware/Racing_systems_microservices/user_microservice/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms1.rule=Host(`ms1.localhost`)"
      - "traefik.http.services.ms1.loadbalancer.server.port=5000" # Cambia el puerto si es necesario
    depends_on:
      - db
    networks:
      - mired2

  db:
    image: postgres:16.2-bullseye
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.db.entrypoints=db"
      - "traefik.tcp.routers.db.rule=HostSNI(`*`)"
      - "traefik.tcp.services.db.loadbalancer.server.port=5432"
    networks:
      - mired2

networks:
  mired2:
    external: true

volumes:
  postgres_data:
    external: true